// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: proto/seckill.proto

package seckill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeckillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillRequest) Reset() {
	*x = SeckillRequest{}
	mi := &file_proto_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillRequest) ProtoMessage() {}

func (x *SeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillRequest.ProtoReflect.Descriptor instead.
func (*SeckillRequest) Descriptor() ([]byte, []int) {
	return file_proto_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SeckillResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Deprecated: Marked as deprecated in proto/seckill.proto.
	OrderId       int64 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // acceptance precedes order creation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResponse) Reset() {
	*x = SeckillResponse{}
	mi := &file_proto_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResponse) ProtoMessage() {}

func (x *SeckillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResponse.ProtoReflect.Descriptor instead.
func (*SeckillResponse) Descriptor() ([]byte, []int) {
	return file_proto_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeckillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/seckill.proto.
func (x *SeckillResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetReservationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationStatusRequest) Reset() {
	*x = GetReservationStatusRequest{}
	mi := &file_proto_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationStatusRequest) ProtoMessage() {}

func (x *GetReservationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetReservationStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *GetReservationStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetReservationStatusRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetReservationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                                 // processing, order_created, recovery_pending, failed
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`             // set only after persistence
	OrderStatus   int32                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"` // 0 pending payment, 1 paid, 2 cancelled, 3 completed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationStatusResponse) Reset() {
	*x = GetReservationStatusResponse{}
	mi := &file_proto_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationStatusResponse) ProtoMessage() {}

func (x *GetReservationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetReservationStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *GetReservationStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetReservationStatusResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetReservationStatusResponse) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

var File_proto_seckill_proto protoreflect.FileDescriptor

const file_proto_seckill_proto_rawDesc = "" +
	"\n" +
	"\x13proto/seckill.proto\x12\aseckill\"d\n" +
	"\x0eSeckillRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"d\n" +
	"\x0fSeckillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\border_id\x18\x03 \x01(\x03B\x02\x18\x01R\aorderId\"U\n" +
	"\x1bGetReservationStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"r\n" +
	"\x1cGetReservationStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\x05R\vorderStatus2\xba\x01\n" +
	"\x0eSeckillService\x12C\n" +
	"\x0eExecuteSeckill\x12\x17.seckill.SeckillRequest\x1a\x18.seckill.SeckillResponse\x12c\n" +
	"\x14GetReservationStatus\x12$.seckill.GetReservationStatusRequest\x1a%.seckill.GetReservationStatusResponseB\x16Z\x14proto_output/seckillb\x06proto3"

var (
	file_proto_seckill_proto_rawDescOnce sync.Once
	file_proto_seckill_proto_rawDescData []byte
)

func file_proto_seckill_proto_rawDescGZIP() []byte {
	file_proto_seckill_proto_rawDescOnce.Do(func() {
		file_proto_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_seckill_proto_rawDesc), len(file_proto_seckill_proto_rawDesc)))
	})
	return file_proto_seckill_proto_rawDescData
}

var file_proto_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_seckill_proto_goTypes = []any{
	(*SeckillRequest)(nil),               // 0: seckill.SeckillRequest
	(*SeckillResponse)(nil),              // 1: seckill.SeckillResponse
	(*GetReservationStatusRequest)(nil),  // 2: seckill.GetReservationStatusRequest
	(*GetReservationStatusResponse)(nil), // 3: seckill.GetReservationStatusResponse
}
var file_proto_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.SeckillService.ExecuteSeckill:input_type -> seckill.SeckillRequest
	2, // 1: seckill.SeckillService.GetReservationStatus:input_type -> seckill.GetReservationStatusRequest
	1, // 2: seckill.SeckillService.ExecuteSeckill:output_type -> seckill.SeckillResponse
	3, // 3: seckill.SeckillService.GetReservationStatus:output_type -> seckill.GetReservationStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_seckill_proto_init() }
func file_proto_seckill_proto_init() {
	if File_proto_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_seckill_proto_rawDesc), len(file_proto_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_seckill_proto_goTypes,
		DependencyIndexes: file_proto_seckill_proto_depIdxs,
		MessageInfos:      file_proto_seckill_proto_msgTypes,
	}.Build()
	File_proto_seckill_proto = out.File
	file_proto_seckill_proto_goTypes = nil
	file_proto_seckill_proto_depIdxs = nil
}
